/* region          = "us-east-1"
subnet_id       = "subnet-09bb946c638fdd9a3"
security_group_id    = "sg-0d56e86ef61a7dc01" */
Name = "test"
Owner =  "TCS"
mailID = "pavan@gmail.com" 
storage_size = "10"
InstanceType = "t2.micro" 
amiId = "ami-051f7e7f6c2f40dc1"
key_name = "terra"
instance_count = 3
security_sg_pub_name = "My-Pub-SG"
security_sg_pri_name = "My-Pri-SG"
