---
- name: Deploy PostgreSQL Helm Chart
  hosts: localhost
  become: yes
  vars:
    helm_chart_name: bitnami/postgresql
    helm_release_name: postgres-testing
    postgres_db_name: platform
    postgres_username: user1
    postgres_password: pass1
    postgres_admin_password: Admin@123
    number_of_replicas: 2
    local_directory_path: /bitnami/postgresql/Tools_intallation_container/

  tasks:
    - name: Check if Helm is installed
      command: helm version --short
      register: helm_version
      ignore_errors: yes

    - name: Install Helm if not installed
      command: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      when: helm_version.rc != 0

    - name: Add Bitnami Helm repository
      command: helm repo add bitnami https://charts.bitnami.com/bitnami
      ignore_errors: yes

    - name: Deploy PostgreSQL Helm Chart
      command: |
        helm upgrade --install {{ helm_release_name }} {{ helm_chart_name }} \
          -- set global.postgresql.auth.postgresPassword={{ postgres_admin_password }} \
          --set  global.postgresql.auth.username={{ postgres_username }} \
          --set  global.postgresql.auth.password={{ postgres_password }} \
          --set global.postgresql.auth.database={{ postgres_db_name }} \
          --set readReplicas.replicaCount={{ number_of_replicas }} \
          --set primary.persistence.existingClaim={{ helm_release_name }}-data \
          --set primary.persistence.mountPath={{ local_directory_path }} \
          --set volumePermissions.enabled=true
      register: helm_install

    - name: Create a NodePort service for PostgreSQL
      command: |
        kubectl expose deployment {{ helm_release_name }} \
          --type=NodePort \
          --name={{ helm_release_name }}-svc
      when: helm_install.rc == 0

- name: PostgreSQL Helm Chart Deployment Complete
  hosts: your_target_host
  tasks:
    - name: Print NodePort service details
      command: kubectl get svc {{ helm_release_name }}-svc -o=json
      register: nodeport_details
      when: helm_install.rc == 0

    - debug:
        var: nodeport_details.stdout
