# Create PV & PVC

apiVersion: v1
kind: PersistentVolume
metadata:
  name: RELEASE_NAME-pv
spec:
  storageClassName: STORAGE_CLASS
  capacity:
    storage: SIZE
  accessModes:
    - ACCESS_MODE
  hostPath:
    path: HOST_PATH
    
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: RELEASE_NAME-pvc
  namespace: RELEASE_NAMESPACE
spec:
  storageClassName: STORAGE_CLASS
  accessModes:
    - ACCESS_MODE
  resources:
    requests:
      storage: SIZE

