
- name: Store IPs in SQL
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Gather instance information
      ec2_instance_info:
        region: us-east-1
        instance_ids: "{{ instance_IDs }}"
      register: ec2_info
    - name: Extract required information
      set_fact:
        instances_data:
          - instance_name: "{{ item.tags.Name }}"
            instance_ip: "{{ item.private_ip_address }}"
            deployment_type: "AWS"
            current_state: "{{ item.state.name }}"
            instance_type: "{{ item.instance_type }}"
      with_items: "{{ ec2_info.instances }}"
    - name: Insert instance information into PostgreSQL
      shell: |
        PGPASSWORD=admin123 psql -h localhost -U postgres -c "INSERT INTO provisioned_instances (instance_name, instance_ip, deployment_type, current_state, instance_type) VALUES ('{{ item.instance_name }}', '{{ item.instance_ip }}', '{{ item.deployment_type }}', '{{ item.current_state }}', '{{ item.instance_type }}');"
      with_items: "{{ instances_data }}"
